### ISSUE TITLE
UE5 - C++ - LNK2019 - Linker Error when calling eny method from ProjectVersionFromGitBPLibrary.h

### ISSUE THREAD

**Issue by sleeptightAnsiC** [mrbindraw/ProjectVersionFromGit#2]
- Occurs only in UE5 when trying to call eny method from ProjectVersionFromGitBPLibrary.h inside of custom C++ class
- Missing macro 'PROJECTVERSIONFROMGIT_API' in ProjectVersionFromGitBPLibrary class declaration
- Fix:
https://github.com/mrbindraw/ProjectVersionFromGit/pull/1

**Comment by mrbindraw** [comment]
Hi!
Thanks for research and fix
I approve your pull request
Have a epic day!
